### ISSUE TITLE
Unable to go to "Saving Objects" section

### ISSUE THREAD

**Issue by chiefGui** [Stamplay/stamplay-js-sdk#10]
When clicking on `Saving Objects` within the `Custom Objects` section, the console outputs

> Uncaught TypeError: Cannot read property 'top' of undefined

and the window doesn't scroll to there.

**Comment by claudiopetrini** [comment]
Hi @chiefGui thanks for reporting. 
For the issues related to the Stamplay Editor please contact us through the question mark at the bottom right of the screen inside the Editor itself.
Thank you
