### ISSUE TITLE
Issue with docs

### ISSUE THREAD

**Issue by mfirry** [Stamplay/stamplay-js-sdk#14]
I spotted a few weird things while reading your docs.

One example is this sentence: *You can create both Model and Collection of Custom Object and Collection has the following additional methods*.

Somewhere else you state *The Collection have some other methods*.

I just thought it'd be helpful for you to know.

Good work anyways!

**Comment by criroselli** [comment]
Hi @mfirry  
thanks for your notice.
Where is exactly this inconsistent part in the readme?
We also accept pull request ;)

**Comment by mfirry** [comment]
Quite frankly, I think it's just bad English... (i.e. "The Collection have..." should be "The Collection has...").

The other sentence ("You can create...")... I just don't understand what it means.

**Comment by criroselli** [comment]
Check the docs now :)

**Comment by mfirry** [comment]
Grazie!
