### ISSUE TITLE
Usage with Webpack (installed via Bower)

### ISSUE THREAD

**Issue by Ridermansb** [Stamplay/stamplay-js-sdk#15]
I'm trying to use the library along with the [Webpack](http://webpack.github.io/) but without success.

I wonder if you can help me. I [created a project on Github](https://github.com/Ridermansb/webpackBowerStarter) that can serve as examples for future reference.

After log `Stamplay` object I can see that `init` function not exist

<img width="555" alt="screen shot 2015-11-04 at 23 35 08" src="https://github-cloud.s3.amazonaws.com/assets%2F725337%2F10957577%2Fcb25adb4-834c-11e5-9c90-ea017207768b.png">

After I fix this, I will add [angular-stamplay](https://github.com/Stamplay/angular-stamplay) support :)

**Comment by alessandroliveri** [comment]
I'm not a Webpack expert but I think the variable called Stamplay is store.js

**Comment by Ridermansb** [comment]
I think that is a stamplay but exactly this code..
 https://github.com/Stamplay/stamplay-js-sdk/blob/master/dist/stamplay.js#L2057

I don't understand why.

**Comment by Ridermansb** [comment]
Maybe this comment can help: http://stackoverflow.com/questions/33502112/webpack-with-bower-support/33553499?noredirect=1#comment54904988_33553499
