### ISSUE TITLE
Logout if the hosting is not provided from Stamplay

### ISSUE THREAD

**Issue by mirkods** [Stamplay/stamplay-js-sdk#20]
If there is an app that use Stamplay only as backend without the hosting the logout method redirect the user on a link with this format: 

 - `http[s]://customdomain.com/auth/v1/logout`

In this case because the host is not provided by Stamplay this means that this endpoint should be implemented on the customer's webserver.

**Comment by mirkods** [comment]
Solved with version 2.0.3!

**Comment by samarthagarwal** [comment]
I could not get it to work. The user is still redirected to 
`http[s]://customdomain.com/auth/v1/auth`.
Let me know if I need to do something else.

**Comment by criroselli** [comment]
@samarthagarwal Do you want an asyncronous logout ?

**Comment by samarthagarwal** [comment]
That would be good. But as of now I don't have a route at `/auth/v1/logout` in my application. So as soon as I (or a user) tries to logout, they get a 404. What are the possible solutions?

PS: It would be great if we could provide a url to redirect to after logout.

**Comment by criroselli** [comment]
Inizialize the sdk with absoluteUrl option: 

`Stamplay.init('APPID', { absoluteUrl: true })`

**Comment by samarthagarwal** [comment]
I just tried that. Still the same problem.

**Comment by criroselli** [comment]
Which version of  the sdk are you using ?

**Comment by samarthagarwal** [comment]
The latest one, 2.0.3. I just updated.

**Comment by criroselli** [comment]
Mmmh it's so strange! Can you give me information about ? 

This is the line of code that manage the redirection 
https://github.com/Stamplay/stamplay-js-sdk/blob/master/src/user.js#L79

**Comment by samarthagarwal** [comment]
Can you give me a code example of how to call the `logout` method asynchronously? I think that something is causing `async` to be `false`.

**Comment by criroselli** [comment]
`Stamplay.User.logout(true, [callback])`

**Comment by samarthagarwal** [comment]
Yes, I am doing the same. I see an error in GET request for /auth/v1/logout and then an immediate redirect to my homepage happens. Half a second later I see this. 
![screenshot_2](https://cloud.githubusercontent.com/assets/3234592/13747081/89a35b70-ea1c-11e5-8953-f6e012e41292.png)

**Comment by criroselli** [comment]
What kind of error ? If you want you can write to me in the Stamplay Slack community or via email

**Comment by samarthagarwal** [comment]
Update: I removed everything from the callback and just placed a `console.log("From Logout Callback")`. Here is the error screenshot.

![screenshot_4](https://cloud.githubusercontent.com/assets/3234592/13747243/5f4cf722-ea1d-11e5-8875-2bf45d375ddf.png)

**Comment by samarthagarwal** [comment]
Kind of working fine for me now. Just getting the error above. Thanks.

**Comment by criroselli** [comment]
Is not an issue on the sdk, please add the custom domain in the cors on editor.stamplay.com
![schermata 2016-03-14 alle 15 18 33](https://cloud.githubusercontent.com/assets/3638712/13747420/7e7f9a3e-e9f8-11e5-9d8f-b642c3c8ab42.png)

**Comment by samarthagarwal** [comment]
The error shows the URL from the Stamplay, not my custom domain. Also the custom domain is already added.

![screenshot_5](https://cloud.githubusercontent.com/assets/3234592/13747639/3875148e-ea1f-11e5-9aad-2c14984c88d6.png)
