### ISSUE TITLE
returning user password

### ISSUE THREAD

**Issue by absolux** [Stamplay/stamplay-js-sdk#29]
`Stamplay.User.get()` returns all users data including `password`, `salt` and `verificationCode`.
I think, it is not a good behavior, for security reason, password and sensitive informations should be hidden.

**Comment by criroselli** [comment]
Do you have an active session in place when you make the call ? Have you changed the permission of user in the Editor ?

**Comment by absolux** [comment]
I tried again, the active user only can see all its data, including password, but not the other users informations.
i am using shared permissions in the editor
