### ISSUE TITLE
TypeError: Stamplay.init is not a function

### ISSUE THREAD

**Issue by kikocastro** [Stamplay/stamplay-js-sdk#3]
Hello, I'm trying to use the SDK on a different domain. When I call Stamplay.init("APPID") as described on the documentation I get TypeError: Stamplay.init is not a function. At the console I get the Stamplay object.

**Comment by claudiopetrini** [comment]
Hi there, what version of the sdk are you using?
Here is an example, please let me know.

**Comment by kikocastro** [comment]
Thank you for the reply! I was having issues with the accepted cors. Using 0.0.12. Now it's working :)

**Comment by claudiopetrini** [comment]
Perfect!
