### ISSUE TITLE
aws-keys.json is required by gruntfile but not included.

### ISSUE THREAD

**Issue by isaiahgrey93** [Stamplay/stamplay-js-sdk#32]
The grunt configuration reads from an `aws-keys.json` file but this file is ignored. Cloning and building will break. Resolved temporarily by adding a empty local `aws-keys.json`.

**Comment by claudiopetrini** [comment]
The file `aws-keys.json` is in the [.gitignore](https://github.com/Stamplay/stamplay-js-sdk/blob/master/.gitignore#L49) to avoid credentials leaks. 
The file is used to get keys for uploading files to S3, and must have `AWSAccessKeyId` and `AWSSecretKey` keys.

**Comment by isaiahgrey93** [comment]
Yes of course. What I meant was that for contributors cloning the project, it will not build until they add an empty aws-keys.json file even though they will not need this file.

**Comment by criroselli** [comment]
Fixed with [#2ea91e7](https://github.com/Stamplay/stamplay-js-sdk/commit/2ea91e7b47b4368d54b2e08a3a2e418f31e132b1)
