### ISSUE TITLE
How to use stamplay with ionic2 ?

### ISSUE THREAD

**Issue by shina** [Stamplay/stamplay-js-sdk#37]
Hello guys, is there a way to use stamplay-sdk with ionic2 (typescript)?

**Comment by jpmsegurado** [comment]
Really need help with this too :(

**Comment by hughred22** [comment]
Same here! Really need Stamplay play nice with Ionic RC1 and typescript... Now all my projects are stuck.... At least give us a timeline so we can decide if we stay with Stamplay or move on to a service which support Ionic2 like Firebase or Auth0.
