### ISSUE TITLE
Stamplay.Query always calls to users object

### ISSUE THREAD

**Issue by aleixpellicer** [Stamplay/stamplay-js-sdk#39]
This:
```
var query = new Stamplay.Query("cobject", "photo");
query.exec().then(function(response){
  console.log(response);
});
```
Does this:

`Request URL:https://foto2.stamplayapp.com/api/cobject/v1/users?where={}`

when it shoud to this:

`Request URL:https://foto2.stamplayapp.com/api/cobject/v1/photo?where={}`

**Comment by criroselli** [comment]
HI @aleixpellicer change "cobject" to "object" :)

Here the reason: 
https://github.com/Stamplay/stamplay-js-sdk/blob/master/src/query.js#L206
