### ISSUE TITLE
Local authentication debugging through oauth

### ISSUE THREAD

**Issue by chiefGui** [Stamplay/stamplay-js-sdk#5]
Hey!

Using the SDK, I'm trying:

```js
var user = new Stamplay.User().Model;

user.login('facebook')
  .then(function () {
    user.get('displayName')
  });
```

But it tries to redirect to `http://myapp.localhost/auth/v1/facebook/connect`, which, for obvious reasons, doesn't exist. What I wanna know is: am I doing something wrong here? Is it impossible to test locally? Or is this a bug? I didn't mine the source yet, but soonish I'll do.

_PS: Even with the wrong redirection, the user is being registered._

**Comment by criroselli** [comment]
Hi @chiefGui,
if you use our cli it's possible. Set your app from Stamplay to handle facebook login, now you can login with this endpoint `http://myapp.localhost/auth/v1/facebook/connect`. After the redirect from facebook you can see on query parameter the stamplay-jwt token. If you want to test the login process you can copy this value and create an entry on local-storage with key http://localhost:8080-jwt and in the value the stamplay-jwt token. Let me know :)

**Comment by chiefGui** [comment]
So, my app is already set to handle Facebook login but when I do the auth it is still redirecting to the Stamplay's endpoint.

**Comment by criroselli** [comment]
The Facebook login process in Stamplay is syncronous call, so it's normal you have a redirect to Facebook and after you return on your app. Actually at this moment we don't have a way to return on local environment, so you will return to the production environment.  A workaround is to login with Facebook from local and as I described you in  the comment above, copy the authentication token in the local environment. Hope that’s more clear now, please let know

**Comment by chiefGui** [comment]
Awesome! It's enough, thanks.
