### ISSUE TITLE
"User" object needs instantiation on a doc's example

### ISSUE THREAD

**Issue by chiefGui** [Stamplay/stamplay-js-sdk#7]
I don't know if this is the right place for reporting [https://stamplay.com/docs/jssdk](https://stamplay.com/docs/jssdk)'s issues, but there you go: in the **Current User**, of **Users** section, the following code is being showed:

```js
var user = Stamplay.User().Model;

user.currentUser()
  .then(function(){
    user.get('displayName');
})
```

The point is: you're not instantiating the `Stamplay.User()` object. According to the [representation](https://github.com/Stamplay/stamplay-js-sdk/blob/master/src/user.js), it is a class and must to be instantiate, otherwise it won't work.

Could you fix it?

The same thing happens for the **Logging Out** section.

_off question: don't you think to open the docs to be updated by your customers/users?_

**Comment by criroselli** [comment]
Thank you @chiefGui ! You are right
