### ISSUE TITLE
The dawn of CORS issues

### ISSUE THREAD

**Issue by chiefGui** [Stamplay/stamplay-js-sdk#8]
Guys!

I am always experiencing issues on developing locally my app because of CORS. I created a vshost called `gabi.dev` and added it in the CORS Enable section of the dashboard and it never works because my app is running on port `:3000` and there's no way to change it to `:80` or `:443`.

Couldn't you enable the capability to specify the ports to enable CORS? `localhost` is not accepted; vshost seems being working only when the port is `:80`. I really don't know how to proceed.

**Comment by claudiopetrini** [comment]
From now on it's possibile to specify in the CORS field a host with an optional port in the format `host.com:3000`.
Another solution it would be to use a virtual host with a properly configured proxy.

**Comment by chiefGui** [comment]
Oh yeah! It's working, @claudiopetrini! Thank you very much!

I think this is the best solution so far—adding the port to the domain—because setting up a vhost could be boring and for the front-enders a pain in the ass.

Anyway, it's working in a straight forward way. Thank you again!

Finally, for those who want to use a vhost, follow the right configuration with a proxy:

```
<VirtualHost *:80>
  ProxyPreserveHost On
  ServerName local.dev
  ProxyPass / http://local.dev:3000/
  ProxyPassReverse / http://localdev:3000/
</VirtualHost>
```

This way, you'll be able to access `http://local.dev` proxying the port `:3000`.
