### ISSUE TITLE
Development version of Facebook's redirect doesn't work locally

### ISSUE THREAD

**Issue by chiefGui** [Stamplay/stamplay-js-sdk#9]
[This line](https://github.com/Stamplay/stamplay-js-sdk/blob/master/src/user.js#L65) uses `document.domain` for the redirection thing, but this doesn't work locally because it'll use the local domain—which doesn't expect that URL.

I didn't create a Pull Request because I am not sure about the best approach to get this issue fixed, but I think `http://[appId].stamplayapp.com/auth/v1/facebook/connect` the right thing to do.

Or am I wrong?

**Comment by criroselli** [comment]
Hi @chiefGui,
now with the version 1.2.9 of Stamplay-js-sdk and lastest version of stamplay-cli (1.3.2) everthings works fine. Thank you
